package com.message;

public enum MessageType {
    USER_CONNECTED, USER_PRESENT, USER_DISCONNECTED, USER_RESTORE_COMMON_MESSAGES, RESTORE_DIRECT_MESSAGES, USER_SEND_COMMON_MESSAGE, USER_SEND_DIRECT_MESSAGE,
}
